spring.application.name=app

server.address=0.0.0.0
server.port=8090
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# DB properties
spring.datasource.url=jdbc:mysql://localhost:3319/overlandwest
spring.datasource.username=dylan
spring.datasource.password=admin

# flyway settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret = 9f7c4c2c8e7f0b1a6d3f9e8a2b5c7d1f4a8b6e9c2d7f1a3b5c8e0f9a2d4b6c7