CREATE TABLE trip_status (
    trip_status_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)