CREATE TABLE trailer (

    trailer_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    length VARCHAR(255),
    trailer_desc VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)